Default: &defaults
  database: order.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: order_test.sqlite3
  <<: *defaults

Staging:
  database: order_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: order_production.sqlite3
  poolsize: 100
  <<: *defaults
